In [ ]:
import numpy as np

In [29]:
arr = [6,7,8,9]
print(type(arr))
print(arr)

print(arr[3])

<class 'list'>
[6, 7, 8, 9]
9


In [6]:
a = np.array(arr)
print(type(a))
print(a.shape)
print(a.dtype)

<class 'numpy.ndarray'>
(4,)
int32


In [7]:
print(a.ndim)

1


In [8]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
print(b.ndim)
print(b.shape)

2
(2, 3)


##### Intra-operability of arrays and scalars.

In [23]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

print(c+d)
print(c*d)
print(5/d)
print(c**2)

print(d[0])


[[13. 13. 13.]
 [10. 10. 10.]]
[[36. 40. 42.]
 [ 9. 16. 21.]]
[[1.25       1.         0.83333333]
 [0.55555556 0.625      0.71428571]]
[[81. 64. 49.]
 [ 1.  4.  9.]]
[4. 5. 6.]


##### Indexing with arrays & using arrays for data processing

In [63]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]], float)
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]], float)

print(d[1,2],)

print(c[1,1])

(c[:2, :1])

7.0
2.0


array([[9.],
       [1.]])

In [55]:
hamoye = np.array([2,3,5,7,9,11])

In [59]:
hamoye

array([ 2,  3,  5,  7,  9, 11])

In [ ]:
hamoye_2 = np.array([[2,3,5], [1,4,6], [7,8,9]])

In [68]:
hamoye_2 [[0,1],[0,2],[2,2]]

NameError: name 'hamoye_2' is not defined